name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
      - name: Setup virtualenv
        run: python3.11 -m venv venv
      - name: update pip setuptools and wheel
        run: venv/bin/python -m pip install --upgrade pip setuptools wheel
      - name: Install local code in edit mode
        run: venv/bin/python -m pip install -e .
      - uses: education/autograding@v1
