name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update pip setuptools and wheel
        run: sudo python -m pip install --upgrade pip setuptools wheel
      - name: Install local code in edit mode
        run: python -m pip install --user -e .
      - uses: education/autograding@v1
